apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: s2-demo-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - image: gcr.io/suzuito-godzilla/s2-demo-api:latest
        resources:
          limits:
            memory: 256Mi
            cpu: 1000m
        env:
        - name: ALLOWED_ORIGINS
          value: https://suzuito-godzilla.web.app
        - name: GH_SHA
          value: ${GITHUB_SHA}
        command: ['/app/main_api/main']
