apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - image: gcr.io/s2-demo-godzilla/api:latest
        resources:
          limits:
            memory: 256Mi
            cpu: 1000m
        env:
        - name: ALLOWED_ORIGINS
          value: https://s2-demo-godzilla.web.app
        - name: GH_SHA
          value: ${GITHUB_SHA}
        command: ['./api.exe']
