name: godzilla-deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: s2-demo-godzilla
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.GCP_PROJECT_ID}}
          service_account_key: ${{ secrets.GCP_SA_KEY_GODZILLA }}
          export_default_credentials: true
      - run: sudo apt-get install gettext-base
      - run: envsubst '${GITHUB_SHA}' < main_api/service-godzilla.yml > k.yml
      - run: gcloud builds submit --tag gcr.io/${{env.GCP_PROJECT_ID}}/go
      - run: gcloud --quiet beta run services replace k.yml --platform managed --region asia-northeast1