name: godzilla-deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_GODZILLA }}
      - run: gcloud builds submit --project=s2-demo-godzilla --config=cloudbuild.yml
      - run: gcloud run deploy s2-demo-go \
               --image gcr.io/s2-demo-godzilla/go \
               --platform managed --region asia-northeast1 --project s2-demo-godzilla \
               --set-env-vars ALLOW_ORIGINS=https://s2-demo-godzilla.web.app \
               --service-account cd-207@s2-demo-godzilla.iam.gserviceaccount.com